
# Generated by CodiumAI
from config.config_util import Configuration
from config.config_util import YamlReadError


import pytest

class TestCodeUnderTest:

    # Configuration object is created successfully
    def test_configuration_object_created_successfully(self):
        config = Configuration()
        assert isinstance(config, Configuration)

    # Config file is read successfully
    def test_config_file_read_successfully(self):
        config = Configuration()
        assert isinstance(config.config, dict)

    # All config attributes are set correctly
    def test_config_attributes_set_correctly(self):
        config = Configuration()
        assert config.telegram_token == "TOKEN"
        assert config.telegram_chat_nr == "CHAT_NUMBER"
        assert config.allowed_user_ids == ["USER_ID_1", "USER_ID_2"]
        assert config.otp_password == "PASSWORD"
        assert config.otp_length == 6
        assert config.otp_interval == 30
        assert config.hash_type == "SHA1"
        assert config.door_bell == 1
        assert config.door_summer == 2
        assert config.blink_username == "USERNAME"
        assert config.blink_password == "PASSWORD"
        assert config.blink_name == "NAME"
        assert config.blink_config_file == "/path/to/config_file.yaml"
        assert config.enable_detect_daylight == True
        assert config.common_image_path == "/path/to/images/"
        assert config.common_camera_type == "CAMERA_TYPE"
        assert config.picam_url == "http://localhost:8000"
        assert config.picam_image_width == 640
        assert config.picam_image_hight == 480
        assert config.picam_image_filename == "image.jpg"
        assert config.picam_exposure == "auto"
        assert config.picam_rotation == 0
        assert config.picam_iso == 100
        assert config.run_on_raspberry == True

    # Config file is not found
    def test_config_file_not_found(self):
        with pytest.raises(FileNotFoundError):
            Configuration()

    # Config file is not in correct format
    def test_config_file_not_in_correct_format(self):
        with pytest.raises(YamlReadError):
            Configuration()

    # TOTP password is not provided
    def test_totp_password_not_provided(self):
        with pytest.raises(KeyError):
            Configuration()